### ISSUE TITLE
Define PAPI presets for AMD Zen4 processors

### ISSUE THREAD

**Issue by sbkathpe** [icl-utk-edu/papi#10]
The file `papi_events.csv` does not define PAPI presets for the AMD Zen4 processor (milan, genoa and the upcoming bergamo).

**Comment by wcohen** [comment]
Thanks for adding the zen4 presents. Looks like there should be PAPI_TOT_INS and PAPI_TOT_CYC in there. That would allow a number of the tests to run on zen4.  Are the PAPI_TOT_INS, PAPI_TOT_CYC, and cache events the things remaining before calling this issue finished?

**Comment by dbarry9** [comment]
Hi Will, that is correct.

**Comment by gcongiu** [comment]
@dbarry9 are there other presets coming for Zen4?

**Comment by gcongiu** [comment]
@dbarry9 is this issue resolved?

**Comment by dbarry9** [comment]
I still have a couple to add in the next few days.

**Comment by Treece-Burgess** [comment]
Closing as PR #125, #128, and #134 add: cache presets, inst cache presets, and total cache presets for Zen 4 respectively.
