### ISSUE TITLE
PAPI configure --with-no-cpu-counters=yes

### ISSUE THREAD

**Issue by anustuvicl** [icl-utk-edu/papi#13]
The PAPI documentation `papi.h:109` states `configure --with-no-cpu-counters=yes` but trying it gives warning
"configure script has no such option".

**Comment by gcongiu** [comment]
Thank you @anustuvicl can you please fix the documentation?

**Comment by anustuvicl** [comment]
I had a discussion with @jagode and @adanalis regarding this. This feature will be reimplemented to match the documentation. We can close this issue for now.
