### ISSUE TITLE
[question] Is PAPI OS-dependant?

### ISSUE THREAD

**Issue by blonded04** [icl-utk-edu/papi#153]
Does PAPI utilize something relevant to OS-specific internals? May I be sure that if using PAPI works well on Linux on one machine, then PAPI will work fine on the same machine on both MacOS and Windows?

**Comment by Treece-Burgess** [comment]
Hello @blonded04 as you stated PAPI will work on Linux; however, PAPI will not work on Windows and as stands MacOS. 

MacOS is lacking support for reading CPU events; but we are currently developing a flag in `./configure` to disable the CPU component such that you could build PAPI on a MAC if it had an NVIDIA or AMD GPU that you would like to work with.
