### ISSUE TITLE
Variation between Fortran files

### ISSUE THREAD

**Issue by cponder** [icl-utk-edu/papi#157]
If I read right, the files under  src/testlib  are F77 compliant, while the 

       src/components/sysdetect/tests/query_device_simple_f.F

is written in F90 format. You special-case this

26    ifeq ($(notdir $(F77)),gfortran)
27         FFLAGS +=-ffree-form -ffree-line-length-none
28     else ifeq ($(notdir $(F77)),flang)
29         FFLAGS +=-ffree-form
30     else ifneq ($(findstring $(notdir $(F77)), $(intel_compilers)),)
31         FFLAGS +=-free
32     else ifneq ($(findstring $(notdir $(F77)), $(cray_compilers)),)
33         FFLAGS +=-ffree
34     endif

in the file

       src/components/sysdetect/tests/Makefile

I'm testing the "nvfortran" compiler, so it's not triggering the corresponding "-Mfree" flag.
And if I set it in general

        export FFLAGS="-noswitcherror -Mfree"

it will try to treat the F77 files as F90 and break the compile.
As I understand the Fortra standard, if you change the name of the latter file to

        src/components/sysdetect/tests/query_device_simple_f.f90

the compilers will automatically treat the file as free-form and you won't have to use the special-casing in the Makefile.

**Comment by cponder** [comment]
I'm using PAPI 7.1.0 with the NVHPC 24.1 compilers.
BTW, it was a lot easier to build this than 6.0.0.

**Comment by adanalis** [comment]
Can you please check in your environment if adding the following two
lines under line 27 in the Makefile solves the problem?

else ifeq ($(notdir $(F77)),nvfortran)
    FFLAGS +=-Mfree


Thanks,
Anthony

**Comment by Treece-Burgess** [comment]
Hello @cponder, was Anthony's suggestion able to solve your issue?

**Comment by Treece-Burgess** [comment]
Closing, if you run into the same or a new issue please feel free to contact us again.
