### ISSUE TITLE
The papi-7.1.0.tar.gz download isn't gzip'd

### ISSUE THREAD

**Issue by cponder** [icl-utk-edu/papi#158]
The tarball here

        https://icl.utk.edu/projects/papi/downloads/papi-7.1.0.tar.gz

posted on this page

        https://icl.utk.edu/papi/

hadn't been gzip'd

        --> gunzip papi-7.1.0.tar.gz
        gzip: papi-7.1.0.tar.gz: not in gzip format

It's a plain tar-file. I noticed this when my install-script broke.

**Comment by cponder** [comment]
Also posted here

       https://github.com/icl-utk-edu/papi/wiki/PAPI-Releases#papi-710-release

with this download-path

        http://icl.utk.edu/projects/papi/downloads/papi-7.1.0.tar.gz

**Comment by adanalis** [comment]
Thank you for bringing this to our attention Carl. It has now been fixed.

Anthony

**Comment by vlopezh** [comment]
Please, update the MD5 hash from the website release notes. I guess it corresponds to the previous one.

Thanks.

**Comment by Treece-Burgess** [comment]
Closing as current release on https://icl.utk.edu/papi/ is gzip'd with correct MD5 hash. I checked the MD5 hash's on the [PAPI Releases](https://github.com/icl-utk-edu/papi/wiki/PAPI-Releases) Wiki page and they were all correct as well.
