### ISSUE TITLE
Trouble adding PAPI_TOT_CYC: Component containing event is disabled after running make test

### ISSUE THREAD

**Issue by kikoveiga** [icl-utk-edu/papi#168]
I was trying to install PAPI on my i7-12700H MSI computer running Ubuntu. I come across this error and can´t get PAPI to run, can anyone help? It doesn´t detect any events, so I can't get past the make test command. 

Available PAPI preset and user defined events plus hardware information.
--------------------------------------------------------------------------------
PAPI version             : 7.1.0.0
Operating system         : Linux 6.5.0-21-generic
Vendor string and code   : GenuineIntel (1, 0x1)
Model string and code    : 12th Gen Intel(R) Core(TM) i7-12700H (154, 0x9a)
CPU revision             : 3.000000
CPUID                    : Family/Model/Stepping 6/154/3, 0x06/0x9a/0x03
CPU Max MHz              : 4600
CPU Min MHz              : 400
Total cores              : 20
SMT threads per core     : 2
Cores per socket         : 10
Sockets                  : 1
Cores per NUMA region    : 20
NUMA regions             : 1
Running in a VM          : no
Number Hardware Counters : 0
Max Multiplex Counters   : 384
Fast counter read (rdpmc): yes
--------------------------------------------------------------------------------

================================================================================
  PAPI Preset Events
================================================================================
    Name        Code    Deriv Description (Note)

--------------------------------------------------------------------------------
Of 0 available events, 0 are derived.

No events detected!  Check papi_component_avail to find out why.

Available components and hardware information.
--------------------------------------------------------------------------------
PAPI version             : 7.1.0.0
Operating system         : Linux 6.5.0-21-generic
Vendor string and code   : GenuineIntel (1, 0x1)
Model string and code    : 12th Gen Intel(R) Core(TM) i7-12700H (154, 0x9a)
CPU revision             : 3.000000
CPUID                    : Family/Model/Stepping 6/154/3, 0x06/0x9a/0x03
CPU Max MHz              : 4600
CPU Min MHz              : 400
Total cores              : 20
SMT threads per core     : 2
Cores per socket         : 10
Sockets                  : 1
Cores per NUMA region    : 20
NUMA regions             : 1
Running in a VM          : no
Number Hardware Counters : 0
Max Multiplex Counters   : 384
Fast counter read (rdpmc): yes
--------------------------------------------------------------------------------

Compiled-in components:
Name:   perf_event              Linux perf_event CPU counters
   \-> Disabled: Error libpfm4 too many default PMUs found
Name:   perf_event_uncore       Linux perf_event CPU uncore and northbridge
   \-> Disabled: No uncore PMUs or events found
Name:   sysdetect               System info detection component

Active components:
Name:   sysdetect               System info detection component
                                Native: 0, Preset: 0, Counters: 0

--------------------------------------------------------------------------------

**Comment by Treece-Burgess** [comment]
Hello @kikoveiga, are you still experiencing this issue?
