### ISSUE TITLE
Qualifiers for ROCm component cause incorrect event count in papi_component_avail

### ISSUE THREAD

**Issue by jagode** [icl-utk-edu/papi#203]
With the introduction of qualifiers for the ROCm component in PAPI version 7.1.0, the "event count" for ROCm in the `papi_component_avail` utility is incorrect.

For instance:
```
rocm:::event
   :device=0
            Mandatory device qualifier [0-7]
```
should still be counted as 8 events in the `papi_component_avail` utility. Right now, it is counted as 1 event.

**Comment by dbarry9** [comment]
This issue has been resolved in #204.
