### ISSUE TITLE
extraneous linkage to libpfm4

### ISSUE THREAD

**Issue by dbarry9** [icl-utk-edu/papi#282]
In the Makefile for the CUDA component tests, there is the line
`PAPILIB += -L../../../libpfm4/lib -lpfm`
which is used for linking for each of the tests.

This linkage is not necessary for the CUDA component tests, and it causes an error when the 'perf_event' and 'perf_event_uncore' components are disabled because libpfm4 is not built.

This may exist in other components' tests, as well.

**Comment by Treece-Burgess** [comment]
We need to make sure we merge a fix for this into master before merging PR #237 from @djwoun.
