### ISSUE TITLE
Out of memory occurs in cat_collect

### ISSUE THREAD

**Issue by Yoshihiro-Furudera** [icl-utk-edu/papi#289]
When cat_collect was run with the -dcr option on PAPI-7.2.0, a memory shortage occurred.
The cat_collect execution environment was ARM64(FUJITSU-MONAKA) Linux, 
and the available memory capacity was approximately 11GB.
To run this test, what is the minimum amount of memory required?
 
Note that cat_collect was run as follows:
`cat_collect -in INPUT_DCR.txt -out OUTPUT_DIR -dcr`

The contents of INPUT_DCR.txt are written as follows:
```
PAPI_L1_DCA 0
PAPI_L1_DCH 0
PAPI_L1_DCM 0
PAPI_L2_DCA 0
PAPI_L2_DCH 0
PAPI_L2_DCM 0
```

The contents of these preset events are the events added in the following pull request.
https://github.com/icl-utk-edu/papi/pull/277
 
I also tried other versions, with the following results.
PAPI-7.1.0: A core dump occurred.
PAPI-7.0.1: Terminated normally.

**Comment by adanalis** [comment]
cat_collect tries to detect the sizes of the caches based on system
information before setting up its buffers. This is the most likely
culprit for the memory errors you are experiencing. In the
counter_analysis_toolkit directory, there is a config file called
.cat_cfg. All the entries are commented out by default, but they are
there to show you the syntax. If you uncomment the lines for the data
caches, such as L3_DCACHE_SIZE, and fill in reasonable values for the
sizes, it should address the problem.

Regards,
Anthony

**Comment by Yoshihiro-Furudera** [comment]
@adanalis 
Thank you for checking.

As you pointed out, uncommenting L3_DCACHE_SIZE in .cat_cfg
and changing it to a smaller value fixed the cat_collect issue.

Best regards.
Yoshihiro Furudera

**Comment by Yoshihiro-Furudera** [comment]
@adanalis 
Thank you for checking.

As you pointed out, uncommenting L3_DCACHE_SIZE in .cat_cfg
and changing it to a smaller value fixed the cat_collect issue.

Best regards.
Yoshihiro Furudera
