### ISSUE TITLE
Remove the unused bundled libpfm-3.y, perfctr-2.6.x, and perfctr-2.7.x source from papi

### ISSUE THREAD

**Issue by wcohen** [icl-utk-edu/papi#50]
PAPI bundles 4 different performance counter access libraries in papi: libpfm4, libpfm-3.y, perfctr-2.6.x, and perfctr-2.7.x.  Of those the only one that has been updated actively in te past decade is libpfm4.  The other three don't appear to be currently used and have not been updated since 2012.  Eliminating the unused perf counter access libraries would remove about 11MB of source, about 30% of the total source code in papi.

**Comment by gcongiu** [comment]
This is tricky because there are components that depend from that code. These components are there for backward compatibility with old systems. I think we should check with @jagode to see what she thinks about removing such libraries from PAPI.

**Comment by wcohen** [comment]
It is good from time to time to clean out stuff that is no longer useful. However, we definitely want to make sure not to break things by taking out functionality still being used.  I don't know all the target systems that papi is being used on and there could be reasons to keep some of these around for continued support. Is the bundled libpfm-3.y actually being built/used. It seems like its functionality would be encompassed by libpfm4?

I see the perfctr and perfctr_ppc components that could be using the perfctr stuff.

**Comment by wcohen** [comment]
I have made a branch, https://github.com/wcohen/papi/tree/wcohen/issue50, which removes the perfctr and libpfm-3.y related files.  It builds fine on Fedora 40 and the /usr/share/papi/run_test.sh results look to be the same as the the results  as PAPI with that code still there.

**Comment by Treece-Burgess** [comment]
Merged PR #191 into master which addresses this issue. @wcohen
