### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by njuhang** [icl-utk-edu/papi#51]
Here are my comands:
git clone --depth 1 --branch papi-6-0-0-1-t https://github.com/icl-utk-edu/papi.git
cd papi/src
./configure 
make -j16
make test

Then an error appears:
make[1]: Leaving directory '/home/lvhang/papi/src/ctests'
ctests/zero
make: *** [Makefile.inc:227: test] Segmentation fault (core dumped)

**Comment by gcongiu** [comment]
Hi @njuhang, could you please try the latest PAPI master branch (or the 7.0.1 release) to see if you can reproduce the problem?

**Comment by njuhang** [comment]
PAPI >  7.0.1 will lead to another problem which I forget what it is. 
Now I solve the problem by apt-get install. 
Thanks a lot

**Comment by gcongiu** [comment]
Could you let us know what the problem with PAPI 7.0.1 is?

**Comment by Treece-Burgess** [comment]
Hello @njuhang, are you still running into the issue noted here:

> PAPI > 7.0.1 will lead to another problem which I forget what it is. Now I solve the problem by apt-get install. Thanks a lot

**Comment by Treece-Burgess** [comment]
Closing, if you run into the same or a new issue please feel free to contact us again.
