### ISSUE TITLE
cuda component overloads field for utility

### ISSUE THREAD

**Issue by anustuvicl** [icl-utk-edu/papi#71]
Pull request [64](https://github.com/icl-utk-edu/papi/pull/62) overloads `num_cntrs` field of `PAPI_component_info_t` to inform `cuda_component_avail` utility that cuda component does not support max counters. 

This implementation introduces potential risk of memory problems in `PAPI_write` and other places. This issue exists to address this problem and bring a different implementation for this feature.

**Comment by jrodgers-github** [comment]
Related issue: https://github.com/icl-utk-edu/papi/issues/61

**Comment by anustuvicl** [comment]
Linked a PR that will revert this feature to having a constant value for max counters. Might need to reopen issue [61](https://github.com/icl-utk-edu/papi/issues/61)
