### ISSUE TITLE
PAPI CUDA: Dangerous `dl_iterate_phdr_cb` operation

### ISSUE THREAD

**Issue by jrodgers-github** [icl-utk-edu/papi#72]
The PAPI CUDA function `src/components/cuda/cupti_common.c::dl_iterate_phdr_cb` is performing a dangerous operation on the resolved `info->dlpi_name`.  Specifically, the call to `dirname()` may modify the contents of the `dlpi_name` when called.

To prevent undesired behavior, the function should be updated to make use of a temporary buffer/copy instead of operating on the `dl_phdr_info` pointer.

Reference: https://linux.die.net/man/3/dirname
> Both dirname() and basename() may modify the contents of path, so it may be desirable to pass a copy when calling one of these functions.

**Comment by anustuvicl** [comment]
Please have a look at the fix. Now copying the string with `strdup` and later freeing it. Not touching the string returned by `dl_iterate_phdr`
