### ISSUE TITLE
PAPI CUDA: `PAPI_read` performance degradation

### ISSUE THREAD

**Issue by jrodgers-github** [icl-utk-edu/papi#85]
Finding a considerable performance degradation for `PAPI_read` operations when using the updated PAPI CUDA component.

Time required by simple benchmark performing 1000 `PAPI_read` operations from 10 executions (by component version):
|version|avg(ms)|min(ms)|max(ms)|
|---|---|---|---|
|old|57428|56444|58584|
|new|326458|325660|327451|

Average performance penalty: 5.68x

Reproducer/benchmark will be attached shortly (please run on y'alls end to confirm behavior).

**Comment by jrodgers-github** [comment]
Attached you will find [issue_85_reproducer.zip](https://github.com/icl-utk-edu/papi/files/12563936/issue_85_reproducer.zip).  Sample compilation from trials:
```
cc  -o issue_85_reproducer.o -c -I/<papi-path>/include ../issue_79_reproducer.c
cc  -o issue_85_reproducer issue_85_reproducer.o -L/<papi-path>/lib64 -lpapi -I/<papi-path>/include
```

Additional trial info:
- Platform with 4 A100's
- CUDA 12.0

**Comment by jrodgers-github** [comment]
From a brief study of the two version of the components, I suspect the addition of full profiling session teardown (`cuptid_control_stop`) and then reconfiguration (`cuptid_control_start`) with each `PAPI_read` is a major contributor to the additional overhead.

**Comment by anustuvicl** [comment]
Thank you for the issue. We are aware of this issue and are actively pursuing to reduce the overhead posed by PAPI_read. We will submit a PR soon.

**Comment by anustuvicl** [comment]
Hi @jrodgers-github, please have a look at the linked PR. This should solve the issue of high overhead. If you find any problems with this fix, please let us know.

**Comment by jrodgers-github** [comment]
Re-ran the same benchmark and found the following behavior using a build from PR99:

|version|avg(ms)|min(ms)|max(ms)|
|---|---|---|---|
|PR99|57757|56755|58717|

Which is much closer to the execution behavior of the old component!

Additionally, playing around with the standard PAPI utilities, `papi_command_line`, `papi_component_avail`, `papi_native_avail`, etc., I'm finding no issues with the proposed change-set.

Thanks for the quick turn around on this topic @anustuvicl!
