### ISSUE TITLE
Define PAPI presets for Intel Sapphire Rapids

### ISSUE THREAD

**Issue by sbkathpe** [icl-utk-edu/papi#9]
[opened this in the bitbucket repository so just repeating to ensure it exists]

The `papi_events.csv` file does not define the PAPI presents for the Sapphire Rapids, ie, `spr`, processor.

**Comment by dbarry9** [comment]
Branch, FLOPs, and other presets for Sapphire Rapids in PR https://github.com/icl-utk-edu/papi/pull/55

There cache-related presets are in the works.

**Comment by dbarry9** [comment]
I will add the cache-related presets in the next few days.

**Comment by Treece-Burgess** [comment]
Closing as PR #135 and PR #138 resolve this issue (completed by Daniel).
